### ISSUE TITLE
Lien en javascript

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [possum-software/possum#123]
Il y a beaucoup de lien en javascript dans les `<li>` : 
Au lieu de :  `<li onclick="window.location=#"> text </li>`
On pourrait utiliser du HTML pur : `<li><a href="#"> text</a></li>`
En rajoutant `display:block;` dans le css des li.

http://openclassrooms.com/forum/sujet/mettre-un-lien-sur-un-li-71819

**Comment by sbonnegent** [comment]
Cela est en cours de changement avec la mise en place de bootstrap dans
possum :)

Le 13 janvier 2015 15:58, Pierre Sassoulas <notifications@github.com> a
écrit :

> Il y a beaucoup de lien en javascript dans les <li> :
> Au lieu de : <li onclick="window.location=#"> text </li>
> On pourrait utiliser du HTML pur : <li><a href="#"> text</a></li>
> En rajoutant display:block; dans le css des li.
>
> http://openclassrooms.com/forum/sujet/mettre-un-lien-sur-un-li-71819
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/possum-software/possum/issues/123>.
>



-- 
Cordialement
Séb. Bonnegent

Pour un format ouvert dans l'éducation: http://formatsouverts.education/

**Comment by sbonnegent** [comment]
Fait dans la version 0.6 bientôt disponible
