### ISSUE TITLE
Sync Github/Sourceforge

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [possum-software/possum#126]
Sourceforge vient de publier un tutoriel pour synchroniser un dépôt github :
http://sourceforge.net/blog/tutorial-how-to-sync-a-github-or-google-code-repo-to-a-sourceforge-project/

**Comment by sbonnegent** [comment]
Ok, mais en quoi cela serait intéressant pour Possum ?

**Comment by Pierre-Sassoulas** [comment]
Je dirais que c'est surtout un plus en terme d'exposition, les grands projets open-sources sont (étaient ?) souvent sur sourceforge.

**Comment by sbonnegent** [comment]
Ok, donc aucun intérêt pour l'instant.
