### ISSUE TITLE
Migration vers Django 1.8

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [possum-software/possum#127]
https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/

C'est une LTS. Si ça ne pose pas de problème de merge avec la branche bootstrap, ça m'intéresse de faire la migration.

**Comment by sbonnegent** [comment]
Oui, pas de problème, tu peux essayer sur la branche dev. Cela dit, les modifications à apporter devraient se limiter au requirements.txt puisque Possum utilise déjà Django 1.7.7

**Comment by Pierre-Sassoulas** [comment]
Apparemment il faudrait renommer certains champs dans le modèle comme "categorie-vat-onsite"
("Related name must be a valid Python identifier or end with a '+'")

On pourrait soit remplacer par  "categorie_vat_onsite" ou par "categorie-vat-onsite+" ?

**Comment by sbonnegent** [comment]
Pour le coup, je préfère la version avec les '_'.

2015-04-09 20:53 GMT+02:00 Pierre Sassoulas <notifications@github.com>:

> Apparemment il faudrait renommer certains champs dans le modèle comme
> "categorie-vat-onsite"
> ("Related name must be a valid Python identifier or end with a '+'")
>
> On pourrait soit remplacer par "categorie_vat_onsite" ou par
> "categorie-vat-onsite+" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/possum-software/possum/issues/127#issuecomment-91326784>
> .
>



-- 
Cordialement
Séb. Bonnegent

Pour un format ouvert dans l'éducation: http://formatsouverts.education/

**Comment by Pierre-Sassoulas** [comment]
Je peux en profiter pour traduire en anglais les champs related_name. Il y a aussi des champs "null" qui n'ont pas d'effet dans les ManyToManyField (nouveau warning avec 1.8).

Par contre il y a besoin de faire une migration, car la base a changé. Peut être pourrait-on remettre le ./make makemigrations dans la partie développeur du make ?

**Comment by Pierre-Sassoulas** [comment]
Il y avait également les fields utilisé dans les Form à définir explicitement. J'ai fait les migrations manuellement (entré dans le virtualenv à la main, puis utilisation du python manage.py, j'ai un peu perdu l'habitude avec le make qui sert de wrapper sans arrêt...). J'ai l'impression que la plupart des fichiers de migrations ont été supprimés, donc j'ai hésité à ne pas add les fichiers de migrations. Il est toujours possible de les enlever.

Je penses que la pull-request peut être merge.

Hors sujet : Je n'avais pas vu ce que donnait la mise à jour de bootstrap avant, c'est vraiment du beau boulot, tout est magnifique par rapport à la version d'avant, même en sachant que c'est juste du css, on a l'impression que ça change tout !

**Comment by sbonnegent** [comment]
Il n'y a pas de "make migrations", il suffit d'utiliser les 3 commandes
dans l'ordre de la partie 'If models changed' dans "developpers"; mais le
message n'est peut etre pas clair. Je vais voir pour expliciter tout ça. Du
coup, il faut aussi que tu ajoutes les nouveaux fichiers de migration et tu
re-pull après exécution des commandes "init_demo" et "create_json_demo".

Sinon, je suis d'accord, c'est beaucoup plus beau avec bootstrap :)

Le 9 avril 2015 21:31, Pierre Sassoulas <notifications@github.com> a écrit :

> Je peux en profiter pour traduire en anglais les champs related_name. Il y
> a aussi des champs "null" qui n'ont pas d'effet dans les ManyToManyField
> (nouveau warning avec 1.8).
>
> Par contre il y a besoin de faire une migration, car la base a changé.
> Peut être pourrait-on remettre le ./make makemigrations dans la partie
> développeur du make ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/possum-software/possum/issues/127#issuecomment-91334712>
> .
>



-- 
Cordialement
Séb. Bonnegent

Pour un format ouvert dans l'éducation: http://formatsouverts.education/

**Comment by Pierre-Sassoulas** [comment]
Ha non, dans ce cas, c'est juste moi qui n'ai pas lu correctement parce que je pensais connaître le makefile. Par contre j'ai eu une erreur en faisant make migrations, et j'ai eu l'impression que le makemigration n'avait pas été réalisé. Vu que le code dans le makefile est censé le faire je vais regarder de plus près.

**Comment by sbonnegent** [comment]
Done
