### ISSUE TITLE
Datetime issue in sqlite

### ISSUE THREAD

**Issue by npettiaux** [possum-software/possum#56]
After a pull this afternoon and a complete reinstallation (new possum.db) and addition of the new components in the virtualenv, I get, just after having changed the rights of the admin user:

/home/pos/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py:53: RuntimeWarning: SQLite received a naive datetime (2013-09-17 16:58:09.217956) while time zone support is active.
  RuntimeWarning)

**Comment by sbonnegent** [comment]
Cela était dû à l'utilisation d'une certaine version de Django et à la non-activation des fuseaux horaires.
